version: '3.7'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    networks:
      - app-network

  jenkins:
    image: "jenkins/jenkins:lts"
    ports:
      - "8081:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - app-network

networks:
  app-network:

volumes:
  jenkins_home:
